### ISSUE TITLE
XML format doesn't work

### ISSUE THREAD

**Issue by MartLintz** [Raival-e/File-Explorer#25]

**Comment by Raival-e** [comment]
If you're talking about the keyboard is not functional after formatting the code, then that's a known (and already fixed) bug related to Sora Editor library, I'm just waiting for the next release of the library that will come with the fix.

Also, could you please provide more info about the issue next time so that I can properly look into it.

**Comment by Raival-e** [comment]
Yeah, xml format isn't fully implemented yet, I'm still waiting for the next release of Sora Editor that will let me extend TextMateLanguage.

**Comment by Raival-e** [comment]
I've temporarily disable XML format option until a new version of Sora Editor comes out.
