### ISSUE TITLE
Compiling files not work properly

### ISSUE THREAD

**Issue by LetsDoNothing** [Raival-e/File-Explorer#28]
https://drive.google.com/file/d/1_kGYuIWAAXmk-1r9qmj3ojuEGc8dc-q3/view?usp=drivesdk

**Comment by Raival-e** [comment]
That's expected, as long as you have a `Main.java/kt` in the same directory, you will be able to run it. This is useful if you have other classes, so that you can run the Main class while you're editing the other ones. That's why I recommended (in README) to create the Main class in an empty folder.
