### ISSUE TITLE
Mixplorer

### ISSUE THREAD

**Issue by missyraja** [Raival-e/File-Explorer#29]
I have been a long time mixplorer user looks like finally something new is brewing to replace it.. hope it gets all the functionality correct.

**Comment by Raival-e** [comment]
Although this app seems similar to Mixplorer, I'm not planning to make a replica of it. But yeah, I'm planning make further improvements and add more features (but those don't necessarily be the same as Mixplorer).

I like Mixplorer, especially the multi-tabs experience and the concept of tasks, and that's why I've featured my file explorer with these two features.

Thanks.

**Comment by missyraja** [comment]
Fair enough. But i was just waiting a long time for a foss replacement for mixplorer with the minimal style. Anyways the project looks promising... 👍👍
